### ISSUE TITLE
callbacks are deprecated

### ISSUE THREAD

**Issue by rafis** [Jemsoft/filesystem-storage-pkgcloud#1]
[Callbacks](https://github.com/Jemsoft/filesystem-storage-pkgcloud/blob/877d0912e0d57e4c8c1a89a3f2176ec8f09bd565/index.js#L176) are [deprecated](https://github.com/pkgcloud/pkgcloud/blob/v1.2.0-0/lib/pkgcloud/amazon/storage/client/files.js#L46-L48). Can you please update?

**Comment by farbodtm** [comment]
Thanks!! We'll look into this.
Pull requests are also more than welcome.
