### ISSUE TITLE
Remote name doesn't function like S3

### ISSUE THREAD

**Issue by bharley** [Jemsoft/filesystem-storage-pkgcloud#2]
If I upload a file using the Amazon S3 provider, I can use a remote like `some/directory/image.jpg` and it will upload without question. If I use the same remote value using this provider, I get a `FileSystemProvider: Invalid name` error.

It would be nice if this adapter (perhaps optionally) attempted to build the directory structure implied by the value of the name.

This should also be the case for other functions (e.g., `getFiles` should build the file list recursively).

**Comment by brandonjmatthews** [comment]
Hi, I have created a PR for this issue #3

**Comment by brandonjmatthews** [comment]
This has been pushed to NPM version 1.2.0
